# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
