# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='relationships',
        ),
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='profiles.Profile'),
        ),
    ]
