# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_favorites'),
        ('profiles', '0002_auto_20160524_0527'),
    ]

    operations = [
    ]
