# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
