# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160523_1628'),
        ('articles', '0004_auto_20160524_0530'),
    ]

    operations = [
    ]
